Add slack-notifier gem
ruby/gem_rbs_collection pull request #286
Opened 2022-12-31 01:38 UTC by yyamanoi1222

Add [slack-notifier](https://github.com/slack-notifier/slack-notifier) gem.

I added only basic interfaces to fulfill a sample code in the README.

2023-01-02 05:09 UTC, pocke approved these changes

2023-01-02 05:23 UTC, pocke requested changes
The CI fails. Could you check the error?

2023-01-03 13:59 UTC, ksss commented on gems/slack-notifier/2.4/manifest.yaml
> +# If all dependencies appear in the gemspec, you should remove this file.
This file does not seem necessary.

2023-01-04 03:56 UTC, pocke approved these changes
thx!

2023-01-04 03:57 UTC, merged